### ISSUE TITLE
convert_example.py

### ISSUE THREAD

**Issue by humoxian** [xinyadu/eeqa#14]
When I try to run convert_example.py (in .proc/) as the proc/README says,it always generate the error:
json.decoder.JSONDecodeError:Expecting property name enclosed in double quotes:line 2 column 1(char 2)
Could anyone tell me why this happened?And how to solve this problem?Thanks!

**Comment by Yonghao-Li** [comment]
I'm facing the same problem as you. How did you solve it?

**Comment by humoxian** [comment]
这样改：




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xinyadu/eeqa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14)





 
I'm facing the same problem as you. How did you solve it?

**Comment by Yonghao-Li** [comment]
I'm sorry to bother you，too. I didn't receive your specific operation.I think my description is inaccurate。





I face the same JSONDecoderError as you did at the beginning. I hope your answer can help me。
Best wishes。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xinyadu/eeqa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 晚上8:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14)





 这样改： 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xinyadu/eeqa"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年5月5日(星期四) 下午2:46 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14) 
 
 
 
 
 
   
 I'm facing the same problem as you. How did you solve it?

**Comment by Yonghao-Li** [comment]
I'm sorry to bother you，too. I didn't receive your specific operation.I think my description is inaccurate。





Traceback (most recent call last):
&nbsp; File "scripts/data/ace-event/convert_examples.py", line 10, in <module&gt;
&nbsp; &nbsp; line = json.loads(line)
&nbsp; File "/root/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
&nbsp; &nbsp; return _default_decoder.decode(s)
&nbsp; File "/root/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode
&nbsp; &nbsp; obj, end = self.raw_decode(s, idx=_w(s, 0).end())
&nbsp; File "/root/miniconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
&nbsp; &nbsp; obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)



I face the same JSONDecoderError as you did at the beginning. I hope your answer can help me。
Best wishes。
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "xinyadu/eeqa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 晚上8:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14)





 这样改： 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "xinyadu/eeqa"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年5月5日(星期四) 下午2:46 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14) 
 
 
 
 
 
   
 I'm facing the same problem as you. How did you solve it?

**Comment by humoxian** [comment]
Please refer to these images on how to fix the JSONDecodeError. If you can't see the attached images, then simply change the Line 749 of parse_ace_event.py from
g.write(json.dumps(js, default=int, indent = 4) + "\n")
to
g.write(json.dumps(js, default=int, indent = None) + "\n").


Best regards.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xinyadu/eeqa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月6日(星期五) 上午9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14)





 I'm sorry to bother you，too. I didn't receive your specific operation.I think my description is inaccurate。 
 
 
 
 
 
 Traceback (most recent call last): 
 &amp;nbsp; File "scripts/data/ace-event/convert_examples.py", line 10, in <module&amp;gt; 
 &amp;nbsp; &amp;nbsp; line = json.loads(line) 
 &amp;nbsp; File "/root/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads 
 &amp;nbsp; &amp;nbsp; return _default_decoder.decode(s) 
 &amp;nbsp; File "/root/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode 
 &amp;nbsp; &amp;nbsp; obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
 &amp;nbsp; File "/root/miniconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode 
 &amp;nbsp; &amp;nbsp; obj, end = self.scan_once(s, idx) 
 json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2) 
 
 
 
 I face the same JSONDecoderError as you did at the beginning. I hope your answer can help me。 
 Best wishes。 
 ------------------ 原始邮件 ------------------ 
 发件人:                                                                                                                        "xinyadu/eeqa"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年5月5日(星期四) 晚上8:37 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14) 
 
 
 
 
 
  这样改：  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "xinyadu/eeqa"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年5月5日(星期四) 下午2:46  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14)  
   
   
   
   
   
     
  I'm facing the same problem as you. How did you solve it?

**Comment by myhcjwds** [comment]
> Please refer to these images on how to fix the JSONDecodeError. If you can't see the attached images, then simply change the Line 749 of parse_ace_event.py from g.write(json.dumps(js, default=int, indent = 4) + "\n") to g.write(json.dumps(js, default=int, indent = None) + "\n"). Best regards.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xinyadu/eeqa" ***@***.***&gt;; 发送时间:&nbsp;2022年5月6日(星期五) 上午9:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14) I'm sorry to bother you，too. I didn't receive your specific operation.I think my description is inaccurate。 Traceback (most recent call last): &amp;nbsp; File "scripts/data/ace-event/convert_examples.py", line 10, in <module&amp;gt; &amp;nbsp; &amp;nbsp; line = json.loads(line) &amp;nbsp; File "/root/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads &amp;nbsp; &amp;nbsp; return _default_decoder.decode(s) &amp;nbsp; File "/root/miniconda3/lib/python3.7/json/decoder.py", line 337, in decode &amp;nbsp; &amp;nbsp; obj, end = self.raw_decode(s, idx=_w(s, 0).end()) &amp;nbsp; File "/root/miniconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode &amp;nbsp; &amp;nbsp; obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2) I face the same JSONDecoderError as you did at the beginning. I hope your answer can help me。 Best wishes。 ------------------ 原始邮件 ------------------ 发件人: "xinyadu/eeqa" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2022年5月5日(星期四) 晚上8:37 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14) 这样改：
> ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 发件人: "xinyadu/eeqa" ***@***.***&amp;amp;gt;; 发送时间:&amp;amp;nbsp;2022年5月5日(星期四) 下午2:46 ***@***.***&amp;amp;gt;; ***@***.******@***.***&amp;amp;gt;; 主题:&amp;amp;nbsp;Re: [xinyadu/eeqa] convert_example.py (Issue #14) I'm facing the same problem as you. How did you solve it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&amp;amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

I have solved it, thanks for your sharing!
